export const SPEED_SCALE = 1.0;

export const state = {
  v0: 0,
  alpha: 0,
  outOfPlaneAngleDeg: 0,
  vz0: 0,
  h: 0,
  x0: 0,
  y0: 0,
  hArrivee: 0,
  g: 0,
  m: 1.0,
  speedFactor: SPEED_SCALE,
  trajectoire: [],
  trajectoire1: [],
  trajectoire2: [],
  isDualTrajectoryMode: false,
  enveloppe: { x: [], y: [] },
  yMax: 0,
  xMaxGraph: 0,
  yMaxGraph: 0,
  porteeX: 0,
  dureeVol: 0,
  tSommet: 0,
  xSommet: 0,
  vImpact: 0,
  eInitiale: 0,
  eImpact: 0,
  currentFrameIndex: 0,
  isPaused: true,
  isUpdating: false,
  animationId: null,
  staticResultsHTML: "",
  mode: "simulation",
  isResistanceActive: false,
  radius: 0.05,
  dragCoeff: 0.47,
  airDensity: 1.225,
  dragModel: "quadratic",
  idealTrajectoire: [],
  showIdealTrajectory: false,
  target: { x: 25, y: 10, z: 0 },
  solutions: [],
  showFinalTrajectory: true,
  simulationStarted: false,
  isDraggingTarget: false,
  showVectors: true,
  startTime: 0,
  showVelocityVectors: true,
  showVelocityComponents: true,
  showVelocityValues: true,
  velocityVectorScale: 0.3,
  projectileShape: "sphere",
  coordSystem: "local", // 'local' par défaut
};

export const DRAG_COEFF_PRESETS = {
  sphere: 0.47,
  cylinder: 1.17,
  bullet: 0.295,
  custom: null,
};
